services:
  airflow:
    build:
      context: ./airflow
      dockerfile: dockerfile
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    volumes:
      - ./airflow:/opt/airflow
    ports:
      - "8081:8080"
    depends_on:
      - postgres
    command: >
      bash -c "
      airflow db upgrade &&
      airflow users create --username admin --password admin --firstname Admin --lastname Admin --role Admin --email admin@example.com &&
      airflow webserver"

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nifi:
    image: custom-nifi:latest  # Image được build từ Dockerfile trên
    build:
      context: ./nifi
    ports:
      - "8443:8443"  # HTTPS port
    environment:
      - NIFI_WEB_HTTPS_PORT=8443
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
    volumes:
      - ./flows:/opt/nifi/nifi-current/flows:rw  # Dùng để upload các file JSON
    restart: unless-stopped




volumes:
  postgres_data:
    external: false

