FROM apache/nifi:latest

USER root

# Cập nhật hệ thống và cài đặt Python3, pip
RUN apt-get update && apt-get install -y \
    python3 python3-pip wget gnupg unzip && \
    rm -rf /var/lib/apt/lists/*

# Cài đặt Google Chrome
RUN wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    apt-get update && apt-get install -y ./google-chrome-stable_current_amd64.deb && \
    ln -s /usr/bin/google-chrome /usr/bin/chrome && \
    chmod +x /usr/bin/google-chrome && \
    rm google-chrome-stable_current_amd64.deb

# Cài đặt Chromedriver
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/chromedriver && \
    rm /tmp/chromedriver.zip

USER nifi
