FROM apache/airflow:latest

# Sử dụng quyền root để cài đặt các phụ thuộc hệ thống
USER root

# Cài đặt git, curl, và Microsoft SQL Server ODBC Driver
RUN apt-get update --fix-missing && \
    apt-get install -y git curl && \
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
    curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list && \
    apt-get update && \
    ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools unixodbc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Quay về user airflow
USER airflow

# Sao chép file requirements.txt và cài đặt các thư viện Python
COPY requirements.txt /tmp/requirements.txt
RUN pip install -r /tmp/requirements.txt

# Cài đặt các thư viện bổ sung
RUN pip install pycountry airflow-code-editor googleads

# Quay lại root để cài đặt Chrome và Chromedriver
USER root

# Cài đặt các thư viện cần thiết cho Chrome và Chromedriver
RUN apt-get update --fix-missing && apt-get install -y \
    wget \
    unzip \
    libgconf-2-4 \
    libnss3 \
    libxss1 \
    libappindicator3-1 \
    fonts-liberation \
    libatk-bridge2.0-0 \
    libatspi2.0-0 \
    libgtk-3-0 \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Cài đặt Google Chrome
# Cài đặt Google Chrome
RUN apt-get update && apt-get install -y wget gnupg unzip && \
    wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb && \
    dpkg -i google-chrome-stable_current_amd64.deb || apt-get -fy install && \
    ln -s /usr/bin/google-chrome /usr/bin/chrome && \
    chmod +x /usr/bin/google-chrome && \
    rm google-chrome-stable_current_amd64.deb

# Cài đặt Chromedriver
RUN wget -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip && \
    unzip /tmp/chromedriver.zip -d /usr/local/bin/ && \
    chmod +x /usr/local/bin/chromedriver && \
    rm /tmp/chromedriver.zip

# Đặt biến môi trường cho Microsoft ODBC Driver
ENV LD_LIBRARY_PATH=/opt/microsoft/msodbcsql17/lib64:$LD_LIBRARY_PATH
ENV PATH="/usr/local/bin:/usr/bin:/bin:${PATH}"

# Quay lại user airflow
USER airflow